//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAcess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gorevler
    {
        public int GorevNo { get; set; }
        public string GorevBaslik { get; set; }
        public string GorevAciklama { get; set; }
        public int RefProjeNo { get; set; }
        public int RefKullaniciNo { get; set; }
        public int RefOncelikNo { get; set; }
        public int RefKategoriNo { get; set; }
        public Nullable<bool> TamamlandiMi { get; set; }
        public Nullable<System.DateTime> BitisTarihi { get; set; }
    
        public virtual Kategoriler Kategoriler { get; set; }
        public virtual Kullanicilar Kullanicilar { get; set; }
        public virtual OncelikDurumlari OncelikDurumlari { get; set; }
        public virtual Projeler Projeler { get; set; }
    }
}
